export enum actionTypes {
    FETCH_PRODUCTS = "FETCH_PRODUCTS",
    RECIEVED_PRODUCTS = "RECIEVED_PRODUCTS",
    CREATE_PRODUCT = "CREATE_PRODUCT",
    CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS",
    UPDATE_PRODUCT = "UPDATE_PRODUCT",
    UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS",
    DELETE_PRODUCT = "DELETE_PRODUCT",
    DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS",
    FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST",
    FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS"
}