export enum actionTypes {
    FETCH_PRODUCTS = "FETCH_PRODUCTS",
    RECIEVED_PRODUCTS = "RECIEVED_PRODUCTS",
    CREATE_PRODUCT = "CREATE_PRODUCT",
    CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
}